export const FETCH_REPORT_REQUEST = "FETCH_REPORT_REQUEST"
export const FETCH_REPORT_SUCCESS = "FETCH_REPORT_SUCCESS"
export const FETCH_REPORT_ERROR = "FETCH_REPORT_ERROR"

// Type For config user or admin

export const CONFIRM_ADMIN = 'CONFIRM_ADMIN'