export const FETCH_REPORT_REQUEST = "FETCH_REPORT_REQUEST"
export const FETCH_REPORT_SUCCESS = "FETCH_REPORT_SUCCESS"
export const FETCH_REPORT_ERROR = "FETCH_REPORT_ERROR"
export const DELETE_REPORT_REQUEST = "DELETE_REPORT_REQUEST"
export const DELETE_REPORT_SUCCESS = "DELETE_REPORT_SUCCESS"
export const DELETE_REPORT_ERROR = "DELETE_REPORT_ERROR"
export const REPORT_DETAIL_REQUEST = "REPORT_DETAIL_REQUEST"
export const REPORT_DETAIL_SUCCESS = "REPORT_DETAIL_SUCCESS"
export const REPORT_DETAIL_ERROR = "REPORT_DETAIL_ERROR"
export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST"
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS"
export const FETCH_POSTS_ERORR = " FETCH_POSTS_ERORR"
export const POSTS_DETAIL_REQUEST = "POSTS_DETAIL_REQUEST "
export const POSTS_DETAIL_SUCCESS = "POSTS_DETAIL_SUCCESS"
export const POST_DETAIL_ERORR = "POST_DETAIL_ERORR"
export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST"
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS"
export const POST_DELETE_ERORR = "POST_DELETE_ERORR"
export const POST_POSTING_REQUEST = "POST_POSTING_REQUEST "
export const POST_POSTING_SUCCESS ="POST_POSTING_SUCCESS"
export const POST_POSTING_ERROR = "POST_POSTING_ERROR"




// Type For config user or admin

export const CONFIRM_ADMIN = 'CONFIRM_ADMIN'